steps:
# ... (otros pasos)
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/ieat-app:$COMMIT_SHA', '.']
  env:
  - 'GOOGLE_API_KEY=${_GOOGLE_API_KEY}'
# ... (resto del archivo)
