Preview

cloudbuild.yaml


steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/ieat-app:$COMMIT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/ieat-app:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'ieat-app'
  - '--image'
  - 'gcr.io/$PROJECT_ID/ieat-app:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  - '--set-env-vars'
  - 'GOOGLE_API_KEY=AIzaSyA53MNCCag3gLPJtInDcX4ptBQn9hDX6gI'
images:
- 'gcr.io/$PROJECT_ID/ieat-app:$COMMIT_SHA'
